apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app
  namespace: spotify-app
  labels:
    app: spotify
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: spotify
  template:
    metadata:
      labels:
        app: spotify
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: spotify
      containers:
        - name: spotify-container
          image: satya1541/redirect:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "info"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-app
  namespace: spotify-app
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: LoadBalancer
  selector:
    app: spotify
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotify-app-hpa
  namespace: spotify-app
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  scaleTargetRef:
    kind: Deployment
    name: spotify-app
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: spotify-app-pdb
  namespace: spotify-app
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: spotify
